/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Autorecord {
	enabled: boolean;
	/**
	 * When toggled on the next transition to 'intermission' (or any of the stop scenes) will be ignored. You will need to switch to a record scene and back to the stop scene for the application to stop recording.
	 */
	ignoreNextStop: boolean;
}
