name: Build

on:
  #push:
    #branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Clone NodeCG
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets['GH_PAT'] }}
        repository: nodecg/nodecg
        ref: 'legacy-1.x'
        path: ./nodecg-temp
    
    # Copies cloned NodeCG into permanent folder.
    # If I didn't do this, some bundles seemed to not actually clone successfully later. 
    - run: cp -r ./nodecg-temp ./nodecg

    # Clone nodecg-speedcontrol (dev branch)
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets['GH_PAT'] }}
        repository: speedcontrol/nodecg-speedcontrol
        ref: 'dev'
        path: ./nodecg/bundles/nodecg-speedcontrol

    # Clone nodecg-obsninja
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets['GH_PAT'] }}
        repository: esamarathon/nodecg-obsninja
        path: ./nodecg/bundles/nodecg-obsninja

    # Clone this repoisitory
    - uses: actions/checkout@v2
      with:
        path: ./nodecg/bundles/esa-layouts

    # Setup some Node stuff
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Install NPM dependencies
    - working-directory: ./nodecg/bundles/esa-layouts
      run: npm ci

    # Build
    - working-directory: ./nodecg/bundles/esa-layouts
      run: npm run build

    # Commit newly built files
    - working-directory: ./nodecg/bundles/esa-layouts
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -f dashboard graphics extension
        git commit -m "Built files" -a

    # Pushes the built files to a specific branch
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets['GH_PAT'] }}
        branch: build
        force: true
        directory: ./nodecg/bundles/esa-layouts
