name: Build

on:
  #push:
    #branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    # Clone NodeCG
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets['GitHub_PAT'] }}
        repository: nodecg/nodecg
        ref: 'legacy-1.x'
        path: ./nodecg-temp
    
    # Copies cloned NodeCG into permanent folder.
    # If I didn't do this, some bundles seemed to not actually clone successfully later. 
    - run: cp -r ./nodecg-temp ./nodecg

    # Clone nodecg-speedcontrol (dev branch)
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets['GitHub_PAT'] }}
        repository: speedcontrol/nodecg-speedcontrol
        ref: 'dev'
        path: ./nodecg/bundles/nodecg-speedcontrol

    # Clone nodecg-obsninja
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets['GitHub_PAT'] }}
        repository: esamarathon/nodecg-obsninja
        path: ./nodecg/bundles/nodecg-obsninja

    # Clone this repoisitory
    - uses: actions/checkout@v2
      with:
        path: ./nodecg/bundles/esa-layouts

    # Setup some Node stuff
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Install NPM dependencies
    - working-directory: ./nodecg/bundles/esa-layouts
      run: npm ci

    # Build
    - working-directory: ./nodecg/bundles/esa-layouts
      run: npm run build
